name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # se ejecuta al hacer push a main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Instalar Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.149.0'

      # 3. Construir el sitio desde la carpeta portafolio
      - name: Build Hugo site
        run: hugo --minify --source ./portafolio

      # 4. Publicar en GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portafolio/public

